---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-cm
  namespace: argo
  labels:
    app: ingress-ikontrol
    component: adapter
data:
  {{- toYaml .Values.config | nindent 2 }}